datasource:
    hikari:
      jdbc-url: jdbc:mysql://brokurly-mysql.cibbkywj3asc.ap-northeast-2.rds.amazonaws.com:3306/cs?useUnicode=true\&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnection=true
      username: root
      password: akzptzjffl1!
      driver-class-name: com.mysql.cj.jdbc.Driver

key:
  aesKey:
    123456789abcdefg123456789abcdefg