spring:
  profiles:
    default: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://brokurly-mysql.cibbkywj3asc.ap-northeast-2.rds.amazonaws.com:3306/co?useUnicode=true\&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnection=true
      username: root
      password: akzptzjffl1!
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database:
      mysql
    generate-ddl:
      false
    hibernate:
      ddl-auto:
        none
    show-sql:
      true
    properties:
      hibernate:
        format_sql:
          true
