spring:
  profiles:
    default: local
    include: local

  jpa:
    database:
      mysql
    generate-ddl:
      false
    hibernate:
      ddl-auto:
        none
    show-sql:
      true
    properties:
      hibernate:
        format_sql:
          true
  spring:
    config:
      activate:
        on-profile:
---

spring:
  profiles:
    default: local

---

spring:
  config:
    activate:
      on-profile: dev


---